changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-changes
    - title: What's Changed 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - '*'
