services:
  postgres:
    image: postgres:15
    container_name: eton-dev-postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: eton-dev
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest # PGAdmin web GUI
    container_name: dev-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eton.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - '8081:80' # open at http://localhost:8081
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin_data:
