/**
 * Phase 7 export renderers: pure string builders over already-loaded DB rows
 * (Persona, Transcript, Run, RunItem). Plain module — NOT 'use server' — the
 * API routes call these and stream the returned string as the response body;
 * the client downloads the bytes and never imports this module (it pulls the
 * db client in transitively via the slider-label import below, so keep it
 * server-side only in practice).
 *
 * Three output families:
 * - Markdown "reports" (context → participant profile → verbatim transcript,
 *   UX-research conventions): NO system prompt and NO model snapshot anywhere
 *   in the text — provenance lives only in the JSON backups below.
 * - Versioned, import-ready JSON backups ('note-next.*-backup') that keep the
 *   system-prompt snapshot + per-session model for a future restore; ids other
 *   than the session id are dropped on purpose (import mints new ULIDs). The
 *   per-session run link (runId) is kept only where the run context is present
 *   — session backups and run backups — because there it is informative; the
 *   persona backup's sessions drop runId (the run itself is absent from that
 *   document, so the value would be a dangling reference after import).
 * - Long-form CSVs (per persona / per run) and the wide run-comparison matrix
 *   (one row per script question, one column per participant).
 *
 * CSV rows use CRLF (Excel-friendly) and NO BOM — the caller routes prepend
 * `\uFEFF` (PERSONA-SCHEMA.md "Export shape": UTF-8 with BOM or Vietnamese
 * opens as mojibake in Excel). JSON is plain UTF-8, also BOM-free (a BOM
 * breaks strict parsers). Markdown carries the research-integrity line at the
 * top of every file (pre-ship checklist, BUILD-PLAN.md).
 */
import {SLIDER_POLAR_LABELS} from '../../db/helper/personas'
import type {Persona, PersonaStatus} from '../../db/schema/personas'
import type {
  PersonalitySliders,
  Run,
  RunItem,
  RunItemStatus,
  RunStatus,
  Transcript,
  TranscriptMode,
  TranscriptTurn,
} from '../../db/schema/transcripts'

/** Verbatim research-integrity header line (pre-ship checklist item). */
const EXPORT_INTEGRITY_LINE =
  'Simulated personas generated by an LLM for research purposes — not real people.'

const CSV_HEADER = [
  'persona_id',
  'persona_name',
  'gender',
  'age',
  'locale',
  'region',
  'income_bracket',
  'occupation',
  'background_tags',
  'calm_anxious',
  'optimistic_cynical',
  'frugal_spendthrift',
  'interview_stance',
  'quirks',
  'run_id',
  'model',
  'turn_index',
  'question',
  'answer',
  'question_time',
  'answer_time',
]

export type QAPair = {
  /** Index within the FILTERED (system turns removed) user/assistant sequence. */
  turnIndex: number
  question: string
  answer: string
  questionTime: string | null
  answerTime: string | null
}

/**
 * Turns → numbered Q&A rows, mirroring the run detail page's
 * formatTranscriptTurns: system turns are bookkeeping, not dialogue. The
 * remaining user/assistant turns pair up consecutively; a trailing user turn
 * (question appended but the assistant turn never landed — offline/timeout)
 * yields a row with an empty answer, and a defensive unpaired assistant turn
 * (should not happen) a row with an empty question.
 *
 * The emitted turnIndex is positional within this filtered sequence. A
 * session with two consecutive user turns (e.g. a double submit) renders the
 * first as an empty-answer row: indices match the raw transcript, not the
 * chat UI's consecutive-turn dedupe. Pairing is kept data-faithful on
 * purpose.
 */
export function qaPairsFromTurns(turns: TranscriptTurn[]): QAPair[] {
  const dialogue = turns.filter((turn) => turn.role !== 'system')
  const pairs: QAPair[] = []
  for (let i = 0; i < dialogue.length; i++) {
    const turn = dialogue[i]!
    if (turn.role === 'user') {
      const next = dialogue[i + 1]
      if (next?.role === 'assistant') {
        pairs.push({
          turnIndex: i,
          question: turn.content,
          answer: next.content,
          questionTime: turn.timestamp,
          answerTime: next.timestamp,
        })
        i++
      } else {
        pairs.push({
          turnIndex: i,
          question: turn.content,
          answer: '',
          questionTime: turn.timestamp,
          answerTime: null,
        })
      }
    } else {
      pairs.push({
        turnIndex: i,
        question: '',
        answer: turn.content,
        questionTime: null,
        answerTime: turn.timestamp,
      })
    }
  }
  return pairs
}

/**
 * RFC 4180 field escaping plus CSV formula-injection mitigation: the value is
 * wrapped in double quotes only when needed (delimiter, quote, newline, or
 * leading/trailing whitespace — quoted fields survive Excel's whitespace
 * trimming) and embedded quotes are doubled. Conditional wrapping keeps rows
 * diffable; wrapping unconditionally is equally correct.
 *
 * A cell whose first character is `=`, `+`, `-`, `@`, tab or CR executes as a
 * formula in Excel, so such values are prefixed with a single quote (the
 * standard text-forcing mitigation) BEFORE the quoting logic — the quote
 * lands inside the cell. The schema's numeric columns (age, sliders 0–100)
 * are never negative, so no legitimate numeric cell starts with `-` and
 * gains a spurious quote.
 */
export function csvEscape(value: string): string {
  const guarded = /^[=+\-@\t\r]/.test(value) ? `'${value}` : value
  if (!/["\n\r,]/.test(guarded) && guarded === guarded.trim()) {
    return guarded
  }
  return `"${guarded.replaceAll('"', '""')}"`
}

/**
 * Stable server-side download-name slug: lowercase, diacritics stripped via
 * NFD decomposition (all Vietnamese tone marks live in U+0300–U+036F), every
 * non-alphanumeric run collapsed to '-'. The server doesn't know the UI
 * locale, so download names are stable-English-safe ASCII ("Trần Thị B" →
 * "tran-thi-b"); the UI note covers localized naming.
 */
export function asciiSlug(value: string): string {
  const slug = value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return slug.length > 0 ? slug : 'persona'
}

/**
 * Markdown inline-safe text: collapse whitespace runs (newlines included) to
 * single spaces and trim. Applied to every heading/label interpolation in the
 * markdown builders so a value containing a newline or a long space run
 * cannot split or corrupt the surrounding markdown block; a stray `#`
 * mid-heading is harmless once the value sits on one line.
 */
export function mdInline(value: string): string {
  return value.replaceAll(/\s+/g, ' ').trim()
}

function emptyWhenNull(value: string | null | undefined): string {
  return value ?? ''
}

/** The persona-level columns shared by every row of one transcript. */
function personaCsvBaseColumns(
  persona: Persona,
  transcript: Transcript,
  runId: string,
): string[] {
  const sliders = persona.personalitySliders
  return [
    persona.id,
    persona.name,
    emptyWhenNull(persona.gender),
    persona.age === null ? '' : String(persona.age),
    persona.locale,
    persona.region,
    emptyWhenNull(persona.incomeBracket),
    emptyWhenNull(persona.occupation),
    persona.backgroundTags.join(';'),
    // Missing axes stay unset for pre-rework rows — never fabricated.
    String(sliders.calm_anxious ?? ''),
    String(sliders.optimistic_cynical ?? ''),
    String(sliders.frugal_spendthrift ?? ''),
    emptyWhenNull(persona.interviewStance),
    emptyWhenNull(persona.quirksFreetext),
    runId,
    // Per-transcript snapshot, not the current config default.
    transcript.model,
  ]
}

function joinCsv(rows: string[][]): string {
  return [CSV_HEADER, ...rows]
    .map((row) => row.map(csvEscape).join(','))
    .join('\r\n')
}

function transcriptCsvRows(
  persona: Persona,
  transcript: Transcript,
  runId: string,
): string[][] {
  const base = personaCsvBaseColumns(persona, transcript, runId)
  return qaPairsFromTurns(transcript.turns).map((pair) => [
    ...base,
    String(pair.turnIndex),
    pair.question,
    pair.answer,
    pair.questionTime ?? '',
    pair.answerTime ?? '',
  ])
}

/** Per-persona CSV — run_id resolves per transcript (null for single sessions). */
export function buildPersonaExportCsv(
  persona: Persona,
  transcripts: Transcript[],
): string {
  const rows = transcripts.flatMap((transcript) =>
    transcriptCsvRows(persona, transcript, transcript.runId ?? ''),
  )
  return joinCsv(rows)
}

/** Per-run CSV — a persona whose item never produced a transcript yields nothing. */
export function buildRunExportCsv(run: Run, items: RunExportItem[]): string {
  const rows = items.flatMap(({persona, transcript}) =>
    transcript ? transcriptCsvRows(persona, transcript, run.id) : [],
  )
  return joinCsv(rows)
}

/** Locale-free UTC stamp from a stored ISO string ("2026-09-27 10:02:03"). */
function shortIso(timestamp: string): string {
  return timestamp.replace('T', ' ').slice(0, 19)
}

/* ------------------------------------------------------------------ */
/* Markdown report builders                                            */
/* ------------------------------------------------------------------ */

/**
 * Numbered Q/A block with locale-free `Q1.`/`A1.` labels; body text stays
 * raw (multi-line answers allowed). A session with turns but no dialogue
 * (or none at all) renders the italic note instead of an empty block.
 */
function qaMarkdownLines(turns: TranscriptTurn[]): string[] {
  const pairs = qaPairsFromTurns(turns)
  if (pairs.length === 0) return ['_No dialogue recorded._']
  const lines: string[] = []
  pairs.forEach((pair, i) => {
    const n = i + 1
    lines.push(`**Q${n}.** ${pair.question}`)
    lines.push(`**A${n}.** ${pair.answer}`)
    lines.push('')
  })
  return lines
}

/**
 * "## Participant Profile" labeled lines; null/empty fields are omitted.
 * Personality axes follow the SLIDER_POLAR_LABELS convention shared with
 * buildActiveRosterSummary: name the pole the value leans toward
 * (>= 50 → the high pole).
 */
function personaProfileLines(persona: Persona): string[] {
  const lines: string[] = [`- Region: ${mdInline(persona.region)}`]
  if (persona.occupation)
    lines.push(`- Occupation: ${mdInline(persona.occupation)}`)
  if (persona.gender) lines.push(`- Gender: ${mdInline(persona.gender)}`)
  if (persona.age !== null) lines.push(`- Age: ${persona.age}`)
  if (persona.incomeBracket)
    lines.push(`- Income Bracket: ${mdInline(persona.incomeBracket)}`)
  if (persona.interviewStance) {
    lines.push(`- Interview Stance: ${mdInline(persona.interviewStance)}`)
  }
  if (persona.backgroundTags.length > 0) {
    lines.push(
      `- Background Tags: ${mdInline(persona.backgroundTags.join(';'))}`,
    )
  }
  for (const key of Object.keys(SLIDER_POLAR_LABELS) as Array<
    keyof typeof SLIDER_POLAR_LABELS
  >) {
    const value: number | undefined = persona.personalitySliders[key]
    if (value === undefined) continue
    const pole = SLIDER_POLAR_LABELS[key][value >= 50 ? 1 : 0]
    lines.push(`- ${key} ${value} — leaning ${pole}`)
  }
  return lines
}

/**
 * Short profile brief for run/session reports: Region + Occupation
 * (Region is NOT NULL in the schema so it always renders), plus Age when
 * `includeAge` (the run participant section wants it, the session brief
 * doesn't).
 */
function personaBriefLines(persona: Persona, includeAge: boolean): string[] {
  const lines: string[] = [`- Region: ${mdInline(persona.region)}`]
  if (persona.occupation)
    lines.push(`- Occupation: ${mdInline(persona.occupation)}`)
  if (includeAge && persona.age !== null) lines.push(`- Age: ${persona.age}`)
  return lines
}

function sessionHeading(transcript: Transcript, ordinal: number): string {
  return `### Session ${ordinal} — ${mdInline(transcript.title?.trim() || 'Untitled')} (${shortIso(transcript.createdAt.toISOString())})`
}

/**
 * Per-persona Markdown report: H1 + exported date + integrity blockquote,
 * Participant Profile, Bio, then one `Session <n>` block per transcript
 * (chronological input order). Provenance (system prompt, model snapshot)
 * is intentionally absent — it belongs to the JSON backup only.
 */
export function buildPersonaExportMarkdown(
  persona: Persona,
  transcripts: Transcript[],
): string {
  const lines: string[] = [
    `# Interview Report — ${mdInline(persona.name)}`,
    '',
    `Exported: ${shortIso(new Date().toISOString())}`,
    '',
    `> ${EXPORT_INTEGRITY_LINE}`,
    '',
    '## Participant Profile',
    '',
    ...personaProfileLines(persona),
  ]
  if (persona.generatedBio?.trim()) {
    lines.push('', '## Bio', '', persona.generatedBio.trim())
  }
  if (transcripts.length > 0) {
    lines.push('', '## Sessions', '')
    transcripts.forEach((transcript, i) => {
      if (i > 0) lines.push('')
      lines.push(
        sessionHeading(transcript, i + 1),
        '',
        ...qaMarkdownLines(transcript.turns),
      )
    })
  }
  return lines.join('\n').trimEnd()
}

export type RunExportItem = {
  item: RunItem
  persona: Persona
  transcript: Transcript | null
}

/**
 * Per-run Markdown report: H1 + integrity blockquote, Overview (research
 * context + N-of-M completion), the numbered interview script, then one
 * participant section per run item. A run holds ONE group transcript per
 * persona — its Q/A renders directly under the participant heading, no
 * Session sub-heading. Items without a completed transcript say so instead
 * of silently rendering an empty participant (error-kind note kept).
 */
export function buildRunExportMarkdown(
  run: Run,
  items: RunExportItem[],
  script: string[],
): string {
  const lines: string[] = [
    `# Interview Report — Run ${shortIso(run.createdAt.toISOString())}`,
    '',
    `> ${EXPORT_INTEGRITY_LINE}`,
    '',
    '## Overview',
    '',
  ]
  if (run.researchContext?.trim()) {
    lines.push(`- Research Context: ${mdInline(run.researchContext)}`)
  }
  const doneCount = items.filter(({item}) => item.status === 'done').length
  lines.push(`- Participants: ${doneCount} of ${items.length} completed`)
  lines.push('', '## Interview Script', '')
  script.forEach((question, i) => {
    lines.push(`${i + 1}. ${mdInline(question)}`)
  })
  lines.push('', '## Participants', '')
  items.forEach(({item, persona, transcript}, i) => {
    if (i > 0) lines.push('')
    lines.push(`### ${mdInline(persona.name)} (${mdInline(item.status)})`, '')
    if (!transcript || item.status !== 'done') {
      // run_items.error holds only a fixed short kind ('timeout',
      // 'persona missing', …): runNextStepAction stores err.kind and
      // never err.message, which can embed the LM Studio endpoint URL.
      // mdInline is defense-in-depth, keeping the note on one line even
      // if a legacy row carried a newline.
      lines.push(
        item.error
          ? `_${mdInline(`No transcript — run item not completed (error: ${item.error}).`)}_`
          : '_No transcript — run item not completed._',
      )
      return
    }
    lines.push(
      ...personaBriefLines(persona, true),
      '',
      ...qaMarkdownLines(transcript.turns),
    )
  })
  return lines.join('\n').trimEnd()
}

/** Per-session Markdown report: H1 + exported date + integrity + brief profile + Q/A. */
export function buildSessionExportMarkdown(
  persona: Persona,
  transcript: Transcript,
): string {
  const lines: string[] = [
    `# Interview Session — ${mdInline(persona.name)}`,
    '',
    `Exported: ${shortIso(new Date().toISOString())}`,
    '',
    `> ${EXPORT_INTEGRITY_LINE}`,
    '',
    ...personaBriefLines(persona, false),
    '',
    ...qaMarkdownLines(transcript.turns),
  ]
  return lines.join('\n').trimEnd()
}

/**
 * Wide comparison matrix for cross-persona analysis: one row per script
 * question (0-based `question_index` + verbatim question — same 0-based
 * convention as the long CSV's `turn_index`), one column per participant in
 * item order. The answer cell reads that persona's transcript turn-pair at
 * the same index — runNextStepAction appends script questions in order, so
 * pair i IS the answer to script question i. Participants without a
 * transcript (or whose transcript is shorter than the script) still get a
 * column; their cells stay empty, never fabricated.
 */
export function buildRunComparisonCsv(
  run: Run,
  items: RunExportItem[],
): string {
  const pairsByItem = items.map(({transcript}) =>
    transcript ? qaPairsFromTurns(transcript.turns) : null,
  )
  const rows: string[][] = [
    ['question_index', 'question', ...items.map(({persona}) => persona.name)],
  ]
  run.questionScript.forEach((question, index) => {
    rows.push([
      String(index),
      question,
      ...pairsByItem.map((pairs) => pairs?.[index]?.answer ?? ''),
    ])
  })
  return rows.map((row) => row.map(csvEscape).join(',')).join('\r\n')
}

/* ------------------------------------------------------------------ */
/* JSON backups                                                        */
/* ------------------------------------------------------------------ */

/**
 * Plain-object persona shape for the versioned JSON backups (no
 * InferSelectModel leak, no persona id — import mints a new ULID).
 * `systemPrompt` may be null (draft personas may not have one yet).
 */
export type PersonaJson = {
  name: string
  gender: string | null
  age: number | null
  locale: string
  region: string
  incomeBracket: string | null
  occupation: string | null
  backgroundTags: string[]
  personalitySliders: PersonalitySliders
  interviewStance: string | null
  quirksFreetext: string | null
  generatedBio: string | null
  systemPrompt: string | null
  status: PersonaStatus
  createdAt: string
  updatedAt: string
}

/** Transcript fields shared by every backup shape (id is the session ULID). */
export type TranscriptJson = {
  id: string
  title: string | null
  mode: TranscriptMode
  model: string
  /** Per-transcript snapshot — never null, unlike the persona-level prompt. */
  systemPrompt: string
  createdAt: string
  turns: TranscriptTurn[]
}

/**
 * Transcript base + its run link (if any). The runId is kept only in shapes
 * where the run context is present — the session backup and the run backup —
 * where it is informative rather than dangling; the persona backup emits
 * plain TranscriptJson sessions without it (see PersonaBackupJson).
 */
export type SessionJson = TranscriptJson & {runId: string | null}

function turnsToJson(turns: TranscriptTurn[]): TranscriptTurn[] {
  return turns.map((turn) => ({
    role: turn.role,
    content: turn.content,
    timestamp: turn.timestamp,
  }))
}

function transcriptBaseToJson(transcript: Transcript): TranscriptJson {
  return {
    id: transcript.id,
    title: transcript.title,
    mode: transcript.mode,
    model: transcript.model,
    systemPrompt: transcript.systemPrompt,
    createdAt: transcript.createdAt.toISOString(),
    turns: turnsToJson(transcript.turns),
  }
}

/** Shared internal mapper — keeps all three backup shapes consistent. */
function personaToJson(persona: Persona): PersonaJson {
  return {
    name: persona.name,
    gender: persona.gender,
    age: persona.age,
    locale: persona.locale,
    region: persona.region,
    incomeBracket: persona.incomeBracket,
    occupation: persona.occupation,
    backgroundTags: [...persona.backgroundTags],
    personalitySliders: {...persona.personalitySliders},
    interviewStance: persona.interviewStance,
    quirksFreetext: persona.quirksFreetext,
    generatedBio: persona.generatedBio,
    systemPrompt: persona.systemPrompt,
    status: persona.status,
    createdAt: persona.createdAt.toISOString(),
    updatedAt: persona.updatedAt.toISOString(),
  }
}

/** Shared internal mapper — keeps the session + run backup shapes consistent. */
function sessionToJson(transcript: Transcript): SessionJson {
  return {...transcriptBaseToJson(transcript), runId: transcript.runId}
}

export type PersonaBackupJson = {
  format: 'note-next.persona-backup'
  version: 1
  exportedAt: string
  integrity: string
  persona: PersonaJson
  /**
   * Plain sessions WITHOUT runId: the run itself is absent from this document
   * and import mints new ULIDs, so a carried-over runId would be a dangling
   * reference with nothing to resolve against.
   */
  sessions: TranscriptJson[]
}

export type RunBackupJson = {
  format: 'note-next.run-backup'
  version: 1
  exportedAt: string
  integrity: string
  run: {
    questionScript: string[]
    researchContext: string | null
    status: RunStatus
    createdAt: string
    updatedAt: string
  }
  participants: Array<{
    status: RunItemStatus
    error: string | null
    persona: PersonaJson
    /** SessionJson keeps runId — the run context is present in this document. */
    transcript: SessionJson | null
  }>
}

export type SessionBackupJson = {
  format: 'note-next.session-backup'
  version: 1
  exportedAt: string
  integrity: string
  persona: PersonaJson
  session: SessionJson
}

/** Versioned, import-ready persona backup: persona + every session (all modes). */
export function buildPersonaExportJson(
  persona: Persona,
  transcripts: Transcript[],
): string {
  const doc: PersonaBackupJson = {
    format: 'note-next.persona-backup',
    version: 1,
    exportedAt: new Date().toISOString(),
    integrity: EXPORT_INTEGRITY_LINE,
    persona: personaToJson(persona),
    // transcriptBaseToJson (no runId): the run is absent from this document
    // and import mints new ULIDs, so a runId would dangle.
    sessions: transcripts.map(transcriptBaseToJson),
  }
  return JSON.stringify(doc, null, 2)
}

/**
 * Versioned, import-ready run backup. `script` is the same array the MD
 * builder receives (the route passes run.questionScript) — kept as the
 * source of the run's questionScript so the MD/JSON builders stay symmetric.
 * Run + participant ids are dropped (import mints new ULIDs); the group
 * transcript's session id is kept as the stable key, and its runId is kept
 * too — the run context is present in this document, making it informative.
 */
export function buildRunExportJson(
  run: Run,
  items: RunExportItem[],
  script: string[],
): string {
  const doc: RunBackupJson = {
    format: 'note-next.run-backup',
    version: 1,
    exportedAt: new Date().toISOString(),
    integrity: EXPORT_INTEGRITY_LINE,
    run: {
      questionScript: script,
      researchContext: run.researchContext,
      status: run.status,
      createdAt: run.createdAt.toISOString(),
      updatedAt: run.updatedAt.toISOString(),
    },
    participants: items.map(({item, persona, transcript}) => ({
      status: item.status,
      error: item.error,
      persona: personaToJson(persona),
      transcript: transcript ? sessionToJson(transcript) : null,
    })),
  }
  return JSON.stringify(doc, null, 2)
}

/** Versioned, import-ready single-session backup: persona + one session. */
export function buildSessionExportJson(
  persona: Persona,
  transcript: Transcript,
): string {
  const doc: SessionBackupJson = {
    format: 'note-next.session-backup',
    version: 1,
    exportedAt: new Date().toISOString(),
    integrity: EXPORT_INTEGRITY_LINE,
    persona: personaToJson(persona),
    session: sessionToJson(transcript),
  }
  return JSON.stringify(doc, null, 2)
}
