/**
 * Phase 7 export renderers: pure string builders over already-loaded DB rows
 * (Persona, Transcript, Run, RunItem). Plain module — NOT 'use server' — the
 * API routes call these and stream the returned string as the response body;
 * the client downloads the bytes and never imports this module (it pulls the
 * db client in transitively via the slider-label import below, so keep it
 * server-side only in practice).
 *
 * Three output families:
 * - Markdown "reports" (context → participant profile → verbatim transcript,
 *   UX-research conventions): NO system prompt and NO model snapshot anywhere
 *   in the text — provenance lives only in the JSON backups below.
 * - Versioned, import-ready JSON backups ('note-next.*-backup') that keep the
 *   system-prompt snapshot + per-session model for a future restore; ids other
 *   than the session id are dropped on purpose (import mints new ULIDs). The
 *   per-session run link (runId) is kept only where the run context is present
 *   — session backups and run backups — because there it is informative; the
 *   persona backup's sessions drop runId (the run itself is absent from that
 *   document, so the value would be a dangling reference after import).
 * - Long-form CSVs (per persona / per run) and the wide run-comparison matrix
 *   (one row per script question, one column per participant).
 *
 * CSV rows use CRLF (Excel-friendly) and NO BOM — the caller routes prepend
 * `\uFEFF` (PERSONA-SCHEMA.md "Export shape": UTF-8 with BOM or Vietnamese
 * opens as mojibake in Excel). JSON is plain UTF-8, also BOM-free (a BOM
 * breaks strict parsers). Markdown carries the research-integrity line at the
 * top of every file (pre-ship checklist, BUILD-PLAN.md).
 */
import {SLIDER_POLAR_LABELS} from '../../db/helper/personas'
import type {Persona, PersonaStatus} from '../../db/schema/personas'
import type {
  PersonalitySliders,
  Run,
  RunItem,
  RunItemStatus,
  RunStatus,
  Transcript,
  TranscriptMode,
  TranscriptTurn,
} from '../../db/schema/transcripts'

/** Verbatim research-integrity header line (pre-ship checklist item). */
// English source of truth. MD reports read ai.interview.export.integrityLine from dictionaries — keep en.json value in sync; JSON backups render this const.
export const EXPORT_INTEGRITY_LINE =
  'Simulated personas generated by an LLM for research purposes, not real people.'

export type QAPair = {
  /** Index within the FILTERED (system turns removed) user/assistant sequence. */
  turnIndex: number
  question: string
  answer: string
  questionTime: string | null
  answerTime: string | null
}

/**
 * Turns → numbered Q&A rows, mirroring the run detail page's
 * formatTranscriptTurns: system turns are bookkeeping, not dialogue. The
 * remaining user/assistant turns pair up consecutively; a trailing user turn
 * (question appended but the assistant turn never landed — offline/timeout)
 * yields a row with an empty answer, and a defensive unpaired assistant turn
 * (should not happen) a row with an empty question.
 *
 * The emitted turnIndex is positional within this filtered sequence. A
 * session with two consecutive user turns (e.g. a double submit) renders the
 * first as an empty-answer row: indices match the raw transcript, not the
 * chat UI's consecutive-turn dedupe. Pairing is kept data-faithful on
 * purpose.
 */
export function qaPairsFromTurns(turns: TranscriptTurn[]): QAPair[] {
  const dialogue = turns.filter((turn) => turn.role !== 'system')
  const pairs: QAPair[] = []
  for (let i = 0; i < dialogue.length; i++) {
    const turn = dialogue[i]!
    if (turn.role === 'user') {
      const next = dialogue[i + 1]
      if (next?.role === 'assistant') {
        pairs.push({
          turnIndex: i,
          question: turn.content,
          answer: next.content,
          questionTime: turn.timestamp,
          answerTime: next.timestamp,
        })
        i++
      } else {
        pairs.push({
          turnIndex: i,
          question: turn.content,
          answer: '',
          questionTime: turn.timestamp,
          answerTime: null,
        })
      }
    } else {
      pairs.push({
        turnIndex: i,
        question: '',
        answer: turn.content,
        questionTime: null,
        answerTime: turn.timestamp,
      })
    }
  }
  return pairs
}

/**
 * RFC 4180 field escaping plus CSV formula-injection mitigation: the value is
 * wrapped in double quotes only when needed (delimiter, quote, newline, or
 * leading/trailing whitespace — quoted fields survive Excel's whitespace
 * trimming) and embedded quotes are doubled. Conditional wrapping keeps rows
 * diffable; wrapping unconditionally is equally correct.
 *
 * A cell whose first character is `=`, `+`, `-`, `@`, tab or CR executes as a
 * formula in Excel, so such values are prefixed with a single quote (the
 * standard text-forcing mitigation) BEFORE the quoting logic — the quote
 * lands inside the cell. The schema's numeric columns (age, sliders 0–100)
 * are never negative, so no legitimate numeric cell starts with `-` and
 * gains a spurious quote.
 */
export function csvEscape(value: string): string {
  const guarded = /^[=+\-@\t\r]/.test(value) ? `'${value}` : value
  if (!/["\n\r,]/.test(guarded) && guarded === guarded.trim()) {
    return guarded
  }
  return `"${guarded.replaceAll('"', '""')}"`
}

/**
 * Stable server-side download-name slug: lowercase, diacritics stripped via
 * NFD decomposition (all Vietnamese tone marks live in U+0300–U+036F), every
 * non-alphanumeric run collapsed to '-'. The server doesn't know the UI
 * locale, so download names are stable-English-safe ASCII ("Trần Thị B" →
 * "tran-thi-b"); the UI note covers localized naming.
 */
export function asciiSlug(value: string): string {
  const slug = value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return slug.length > 0 ? slug : 'persona'
}

/**
 * Markdown inline-safe text: collapse whitespace runs (newlines included) to
 * single spaces and trim. Applied to every heading/label interpolation in the
 * markdown builders so a value containing a newline or a long space run
 * cannot split or corrupt the surrounding markdown block; a stray `#`
 * mid-heading is harmless once the value sits on one line.
 */
export function mdInline(value: string): string {
  return value.replaceAll(/\s+/g, ' ').trim()
}

function emptyWhenNull(value: string | null | undefined): string {
  return value ?? ''
}

/** The persona-level columns shared by every row of one transcript. */
function personaCsvBaseColumns(persona: Persona, runId: string): string[] {
  const sliders = persona.personalitySliders
  return [
    persona.id,
    persona.name,
    emptyWhenNull(persona.gender),
    persona.age === null ? '' : String(persona.age),
    persona.locale,
    persona.region,
    emptyWhenNull(persona.incomeBracket),
    emptyWhenNull(persona.occupation),
    persona.backgroundTags.join(';'),
    // Missing axes stay unset for pre-rework rows — never fabricated.
    String(sliders.calm_anxious ?? ''),
    String(sliders.optimistic_cynical ?? ''),
    String(sliders.frugal_spendthrift ?? ''),
    emptyWhenNull(persona.interviewStance),
    emptyWhenNull(persona.quirksFreetext),
    runId,
  ]
}

/**
 * Localized header row (label-driven, same column order as
 * personaCsvBaseColumns + the per-pair columns). Header count and row count
 * stay in lockstep: 14 persona-level cells + run_id + 5 pair cells = 20.
 */
function csvHeader(labels: ReportLabels): string[] {
  const poles = labels.sliderPoles
  return [
    labels.csv.personaId,
    labels.csv.personaName,
    labels.attrs.gender,
    labels.attrs.age,
    labels.csv.locale,
    labels.attrs.region,
    labels.attrs.income,
    labels.attrs.occupation,
    labels.attrs.tags,
    `${poles.calm} / ${poles.anxious}`,
    `${poles.optimistic} / ${poles.cynical}`,
    `${poles.frugal} / ${poles.spendthrift}`,
    labels.attrs.stance,
    labels.attrs.quirks,
    labels.csv.runId,
    labels.csv.turnIndex,
    labels.csv.question,
    labels.csv.answer,
    labels.csv.questionTime,
    labels.csv.answerTime,
  ]
}

function joinCsv(header: string[], rows: string[][]): string {
  return [header, ...rows]
    .map((row) => row.map(csvEscape).join(','))
    .join('\r\n')
}

function transcriptCsvRows(
  persona: Persona,
  transcript: Transcript,
  runId: string,
): string[][] {
  const base = personaCsvBaseColumns(persona, runId)
  return qaPairsFromTurns(transcript.turns).map((pair) => [
    ...base,
    String(pair.turnIndex),
    pair.question,
    pair.answer,
    pair.questionTime ?? '',
    pair.answerTime ?? '',
  ])
}

/** Per-persona CSV — run_id resolves per transcript (null for single sessions). */
export function buildPersonaExportCsv(
  persona: Persona,
  transcripts: Transcript[],
  labels: ReportLabels,
): string {
  const rows = transcripts.flatMap((transcript) =>
    transcriptCsvRows(persona, transcript, transcript.runId ?? ''),
  )
  return joinCsv(csvHeader(labels), rows)
}

/** Per-run CSV — a persona whose item never produced a transcript yields nothing. */
export function buildRunExportCsv(
  run: Run,
  items: RunExportItem[],
  labels: ReportLabels,
): string {
  const rows = items.flatMap(({persona, transcript}) =>
    transcript ? transcriptCsvRows(persona, transcript, run.id) : [],
  )
  return joinCsv(csvHeader(labels), rows)
}

/** Locale-free UTC stamp from a stored ISO string ("2026-09-27 10:02:03"). */
function shortIso(timestamp: string): string {
  return timestamp.replace('T', ' ').slice(0, 19)
}

/* ------------------------------------------------------------------ */
/* Markdown report builders                                            */
/* ------------------------------------------------------------------ */

/**
 * Localizable strings for the Markdown report builders. lib/ai/export.ts
 * stays pure (no next-intl import): the API routes resolve the labels via
 * buildReportLabels (lib/ai/report-labels.ts) and pass them in, because
 * routes live outside the [locale] segment and read the locale from the
 * `?locale=` query param.
 */
export type ReportLabels = {
  personaTitle: (name: string) => string
  sessionTitle: (name: string) => string
  runTitle: (stamp: string) => string
  sessionHeading: (n: number, title: string, stamp: string) => string
  exportedLine: (stamp: string) => string
  integrityLine: string
  participantProfile: string
  overview: string
  researchContext: string
  interviewScript: string
  participantsHeading: string
  participantsCompleted: (done: number, total: number) => string
  sessions: string
  untitled: string
  noDialogue: string
  leaning: string
  genderUnspecified: string
  attrs: {
    region: string
    occupation: string
    gender: string
    age: string
    income: string
    stance: string
    tags: string
    quirks: string
    bio: string
  }
  options: {
    gender: Record<string, string | undefined>
    income: Record<string, string | undefined>
    stance: Record<string, string | undefined>
  }
  sliderPoles: {
    calm: string
    anxious: string
    optimistic: string
    cynical: string
    frugal: string
    spendthrift: string
  }
  /** Localized CSV header labels (same column order as csvHeader). */
  csv: {
    personaId: string
    personaName: string
    locale: string
    runId: string
    turnIndex: string
    question: string
    answer: string
    questionTime: string
    answerTime: string
    questionIndex: string
  }
  /** Run-item status → localized label; unknown statuses print raw. */
  runItemStatus: Record<string, string>
  noTranscript: string
  noTranscriptError: (error: string) => string
}

/**
 * Slider axis (SLIDER_POLAR_LABELS key) → the low/high pole keys in
 * ReportLabels.sliderPoles. Same pairing as the slider UI's axes.
 */
const SLIDER_POLE_LABEL_KEYS: Record<
  keyof typeof SLIDER_POLAR_LABELS,
  [keyof ReportLabels['sliderPoles'], keyof ReportLabels['sliderPoles']]
> = {
  calm_anxious: ['calm', 'anxious'],
  optimistic_cynical: ['optimistic', 'cynical'],
  frugal_spendthrift: ['frugal', 'spendthrift'],
}

/** Canonical option key → localized label; unknown keys print raw values. */
function optionLabel(
  options: Record<string, string | undefined>,
  value: string,
): string {
  return options[value] ?? value
}

/**
 * Numbered Q/A block with locale-free `Q1.`/`A1.` labels; body text stays
 * raw (multi-line answers allowed). A blank line separates the question and
 * answer lines (and each pair from the next) so rendered markdown shows
 * them as distinct paragraphs, not one soft-wrapped block. A session with
 * turns but no dialogue (or none at all) renders the italic note instead of
 * an empty block.
 */
function qaMarkdownLines(
  turns: TranscriptTurn[],
  labels: ReportLabels,
): string[] {
  const pairs = qaPairsFromTurns(turns)
  if (pairs.length === 0) return [`_${labels.noDialogue}_`]
  const lines: string[] = []
  pairs.forEach((pair, i) => {
    const n = i + 1
    lines.push(`**Q${n}.** ${pair.question}`)
    lines.push('')
    lines.push(`**A${n}.** ${pair.answer}`)
    lines.push('')
  })
  return lines
}

/**
 * "## <participantProfile>" labeled lines; null/empty fields are omitted —
 * gender excepted, which falls back to the explicit "unspecified" label
 * (matching the persona profile page). Personality axes follow the
 * SLIDER_POLAR_LABELS convention shared with buildActiveRosterSummary: name
 * the pole the value leans toward (>= 50 → the high pole).
 */
function personaProfileLines(persona: Persona, labels: ReportLabels): string[] {
  const lines: string[] = [
    `- ${labels.attrs.region}: ${mdInline(persona.region)}`,
  ]
  if (persona.occupation)
    lines.push(`- ${labels.attrs.occupation}: ${mdInline(persona.occupation)}`)
  lines.push(
    `- ${labels.attrs.gender}: ${
      persona.gender
        ? mdInline(optionLabel(labels.options.gender, persona.gender))
        : labels.genderUnspecified
    }`,
  )
  if (persona.age !== null) lines.push(`- ${labels.attrs.age}: ${persona.age}`)
  if (persona.incomeBracket)
    lines.push(
      `- ${labels.attrs.income}: ${mdInline(
        optionLabel(labels.options.income, persona.incomeBracket),
      )}`,
    )
  if (persona.interviewStance)
    lines.push(
      `- ${labels.attrs.stance}: ${mdInline(
        optionLabel(labels.options.stance, persona.interviewStance),
      )}`,
    )
  if (persona.backgroundTags.length > 0) {
    lines.push(
      `- ${labels.attrs.tags}: ${mdInline(persona.backgroundTags.join(';'))}`,
    )
  }
  if (persona.quirksFreetext) {
    lines.push(`- ${labels.attrs.quirks}: ${mdInline(persona.quirksFreetext)}`)
  }
  for (const key of Object.keys(SLIDER_POLAR_LABELS) as Array<
    keyof typeof SLIDER_POLAR_LABELS
  >) {
    const value: number | undefined = persona.personalitySliders[key]
    if (value === undefined) continue
    const [low, high] = SLIDER_POLE_LABEL_KEYS[key]
    const lowPole = labels.sliderPoles[low]
    const highPole = labels.sliderPoles[high]
    const leaningPole = value >= 50 ? highPole : lowPole
    lines.push(
      `- ${lowPole} / ${highPole}: ${value} - ${labels.leaning} ${leaningPole}`,
    )
  }
  return lines
}

/**
 * Short profile brief for run reports: Region + Occupation (Region is NOT
 * NULL in the schema so it always renders), plus Age when `includeAge`.
 */
function personaBriefLines(
  persona: Persona,
  includeAge: boolean,
  labels: ReportLabels,
): string[] {
  const lines: string[] = [
    `- ${labels.attrs.region}: ${mdInline(persona.region)}`,
  ]
  if (persona.occupation)
    lines.push(`- ${labels.attrs.occupation}: ${mdInline(persona.occupation)}`)
  if (includeAge && persona.age !== null)
    lines.push(`- ${labels.attrs.age}: ${persona.age}`)
  return lines
}

function sessionHeading(
  transcript: Transcript,
  ordinal: number,
  labels: ReportLabels,
): string {
  return `### ${labels.sessionHeading(
    ordinal,
    mdInline(transcript.title?.trim() || labels.untitled),
    shortIso(transcript.createdAt.toISOString()),
  )}`
}

/**
 * Per-persona Markdown report: H1 + exported date + integrity blockquote,
 * Participant Profile, Bio, then one `Session <n>` block per transcript
 * (chronological input order). Provenance (system prompt, model snapshot)
 * is intentionally absent — it belongs to the JSON backup only.
 */
export function buildPersonaExportMarkdown(
  persona: Persona,
  transcripts: Transcript[],
  labels: ReportLabels,
): string {
  const lines: string[] = [
    `# ${labels.personaTitle(mdInline(persona.name))}`,
    '',
    labels.exportedLine(shortIso(new Date().toISOString())),
    '',
    `> ${labels.integrityLine}`,
    '',
    `## ${labels.participantProfile}`,
    '',
    ...personaProfileLines(persona, labels),
  ]
  if (persona.generatedBio?.trim()) {
    lines.push('', `## ${labels.attrs.bio}`, '', persona.generatedBio.trim())
  }
  if (transcripts.length > 0) {
    lines.push('', `## ${labels.sessions}`, '')
    transcripts.forEach((transcript, i) => {
      if (i > 0) lines.push('')
      lines.push(
        sessionHeading(transcript, i + 1, labels),
        '',
        ...qaMarkdownLines(transcript.turns, labels),
      )
    })
  }
  return lines.join('\n').trimEnd()
}

export type RunExportItem = {
  item: RunItem
  persona: Persona
  transcript: Transcript | null
}

/**
 * Per-run Markdown report: H1 + integrity blockquote, Overview (research
 * context + N-of-M completion), the numbered interview script, then one
 * participant section per run item. A run holds ONE group transcript per
 * persona — its Q/A renders directly under the participant heading, no
 * Session sub-heading. Items without a completed transcript say so instead
 * of silently rendering an empty participant (error-kind note kept).
 */
export function buildRunExportMarkdown(
  run: Run,
  items: RunExportItem[],
  script: string[],
  labels: ReportLabels,
): string {
  const lines: string[] = [
    `# ${labels.runTitle(shortIso(run.createdAt.toISOString()))}`,
    '',
    `> ${labels.integrityLine}`,
    '',
    `## ${labels.overview}`,
    '',
  ]
  if (run.researchContext?.trim()) {
    lines.push(`- ${labels.researchContext}: ${mdInline(run.researchContext)}`)
  }
  const doneCount = items.filter(({item}) => item.status === 'done').length
  lines.push(`- ${labels.participantsCompleted(doneCount, items.length)}`)
  lines.push('', `## ${labels.interviewScript}`, '')
  script.forEach((question, i) => {
    lines.push(`${i + 1}. ${mdInline(question)}`)
  })
  lines.push('', `## ${labels.participantsHeading}`, '')
  items.forEach(({item, persona, transcript}, i) => {
    if (i > 0) lines.push('')
    lines.push(
      `### ${mdInline(persona.name)} (${mdInline(
        labels.runItemStatus[item.status] ?? item.status,
      )})`,
      '',
    )
    if (!transcript || item.status !== 'done') {
      // run_items.error holds only a fixed short kind ('timeout',
      // 'persona missing', …): runNextStepAction stores err.kind and
      // never err.message, which can embed the LM Studio endpoint URL.
      // mdInline is defense-in-depth, keeping the note on one line even
      // if a legacy row carried a newline.
      lines.push(
        item.error
          ? `_${mdInline(labels.noTranscriptError(item.error))}_`
          : `_${labels.noTranscript}_`,
      )
      return
    }
    lines.push(
      ...personaBriefLines(persona, true, labels),
      '',
      ...qaMarkdownLines(transcript.turns, labels),
    )
  })
  return lines.join('\n').trimEnd()
}

/**
 * Per-session Markdown report: H1 + exported date + integrity, then the SAME
 * full persona profile + Bio sections as the persona report, followed by the
 * session's Q/A (no Session sub-heading — a lone session has no siblings).
 */
export function buildSessionExportMarkdown(
  persona: Persona,
  transcript: Transcript,
  labels: ReportLabels,
): string {
  const lines: string[] = [
    `# ${labels.sessionTitle(mdInline(persona.name))}`,
    '',
    labels.exportedLine(shortIso(new Date().toISOString())),
    '',
    `> ${labels.integrityLine}`,
    '',
    `## ${labels.participantProfile}`,
    '',
    ...personaProfileLines(persona, labels),
  ]
  if (persona.generatedBio?.trim()) {
    lines.push('', `## ${labels.attrs.bio}`, '', persona.generatedBio.trim())
  }
  lines.push('', ...qaMarkdownLines(transcript.turns, labels))
  return lines.join('\n').trimEnd()
}

/**
 * Wide comparison matrix for cross-persona analysis: one row per script
 * question (0-based index + verbatim question — same 0-based convention as
 * the long CSV's turn index; the two header cells are localized labels), one
 * column per participant in item order. The answer cell reads that persona's
 * transcript turn-pair at the same index — runNextStepAction appends script questions in order, so
 * pair i IS the answer to script question i. Participants without a
 * transcript (or whose transcript is shorter than the script) still get a
 * column; their cells stay empty, never fabricated.
 */
export function buildRunComparisonCsv(
  run: Run,
  items: RunExportItem[],
  labels: ReportLabels,
): string {
  const pairsByItem = items.map(({transcript}) =>
    transcript ? qaPairsFromTurns(transcript.turns) : null,
  )
  const rows: string[][] = [
    [
      labels.csv.questionIndex,
      labels.csv.question,
      ...items.map(({persona}) => persona.name),
    ],
  ]
  run.questionScript.forEach((question, index) => {
    rows.push([
      String(index),
      question,
      ...pairsByItem.map((pairs) => pairs?.[index]?.answer ?? ''),
    ])
  })
  return rows.map((row) => row.map(csvEscape).join(',')).join('\r\n')
}

/* ------------------------------------------------------------------ */
/* JSON backups                                                        */
/* ------------------------------------------------------------------ */

/**
 * Plain-object persona shape for the versioned JSON backups (no
 * InferSelectModel leak, no persona id — import mints a new ULID).
 * `systemPrompt` may be null (draft personas may not have one yet).
 */
export type PersonaJson = {
  name: string
  gender: string | null
  age: number | null
  locale: string
  region: string
  incomeBracket: string | null
  occupation: string | null
  backgroundTags: string[]
  personalitySliders: PersonalitySliders
  interviewStance: string | null
  quirksFreetext: string | null
  generatedBio: string | null
  systemPrompt: string | null
  status: PersonaStatus
  createdAt: string
  updatedAt: string
}

/** Transcript fields shared by every backup shape (id is the session ULID). */
export type TranscriptJson = {
  id: string
  title: string | null
  mode: TranscriptMode
  model: string
  /** Per-transcript snapshot — never null, unlike the persona-level prompt. */
  systemPrompt: string
  createdAt: string
  turns: TranscriptTurn[]
}

/**
 * Transcript base + its run link (if any). The runId is kept only in shapes
 * where the run context is present — the session backup and the run backup —
 * where it is informative rather than dangling; the persona backup emits
 * plain TranscriptJson sessions without it (see PersonaBackupJson).
 */
export type SessionJson = TranscriptJson & {runId: string | null}

function turnsToJson(turns: TranscriptTurn[]): TranscriptTurn[] {
  return turns.map((turn) => ({
    role: turn.role,
    content: turn.content,
    timestamp: turn.timestamp,
  }))
}

function transcriptBaseToJson(transcript: Transcript): TranscriptJson {
  return {
    id: transcript.id,
    title: transcript.title,
    mode: transcript.mode,
    model: transcript.model,
    systemPrompt: transcript.systemPrompt,
    createdAt: transcript.createdAt.toISOString(),
    turns: turnsToJson(transcript.turns),
  }
}

/** Shared internal mapper — keeps all three backup shapes consistent. */
function personaToJson(persona: Persona): PersonaJson {
  return {
    name: persona.name,
    gender: persona.gender,
    age: persona.age,
    locale: persona.locale,
    region: persona.region,
    incomeBracket: persona.incomeBracket,
    occupation: persona.occupation,
    backgroundTags: [...persona.backgroundTags],
    personalitySliders: {...persona.personalitySliders},
    interviewStance: persona.interviewStance,
    quirksFreetext: persona.quirksFreetext,
    generatedBio: persona.generatedBio,
    systemPrompt: persona.systemPrompt,
    status: persona.status,
    createdAt: persona.createdAt.toISOString(),
    updatedAt: persona.updatedAt.toISOString(),
  }
}

/** Shared internal mapper — keeps the session + run backup shapes consistent. */
function sessionToJson(transcript: Transcript): SessionJson {
  return {...transcriptBaseToJson(transcript), runId: transcript.runId}
}

export type PersonaBackupJson = {
  format: 'note-next.persona-backup'
  version: 1
  exportedAt: string
  integrity: string
  persona: PersonaJson
  /**
   * Plain sessions WITHOUT runId: the run itself is absent from this document
   * and import mints new ULIDs, so a carried-over runId would be a dangling
   * reference with nothing to resolve against.
   */
  sessions: TranscriptJson[]
}

export type RunBackupJson = {
  format: 'note-next.run-backup'
  version: 1
  exportedAt: string
  integrity: string
  run: {
    questionScript: string[]
    researchContext: string | null
    status: RunStatus
    createdAt: string
    updatedAt: string
  }
  participants: Array<{
    status: RunItemStatus
    error: string | null
    persona: PersonaJson
    /** SessionJson keeps runId — the run context is present in this document. */
    transcript: SessionJson | null
  }>
}

export type SessionBackupJson = {
  format: 'note-next.session-backup'
  version: 1
  exportedAt: string
  integrity: string
  persona: PersonaJson
  session: SessionJson
}

/** Versioned, import-ready persona backup: persona + every session (all modes). */
export function buildPersonaExportJson(
  persona: Persona,
  transcripts: Transcript[],
): string {
  const doc: PersonaBackupJson = {
    format: 'note-next.persona-backup',
    version: 1,
    exportedAt: new Date().toISOString(),
    integrity: EXPORT_INTEGRITY_LINE,
    persona: personaToJson(persona),
    // transcriptBaseToJson (no runId): the run is absent from this document
    // and import mints new ULIDs, so a runId would dangle.
    sessions: transcripts.map(transcriptBaseToJson),
  }
  return JSON.stringify(doc, null, 2)
}

/**
 * Versioned, import-ready run backup. `script` is the same array the MD
 * builder receives (the route passes run.questionScript) — kept as the
 * source of the run's questionScript so the MD/JSON builders stay symmetric.
 * Run + participant ids are dropped (import mints new ULIDs); the group
 * transcript's session id is kept as the stable key, and its runId is kept
 * too — the run context is present in this document, making it informative.
 */
export function buildRunExportJson(
  run: Run,
  items: RunExportItem[],
  script: string[],
): string {
  const doc: RunBackupJson = {
    format: 'note-next.run-backup',
    version: 1,
    exportedAt: new Date().toISOString(),
    integrity: EXPORT_INTEGRITY_LINE,
    run: {
      questionScript: script,
      researchContext: run.researchContext,
      status: run.status,
      createdAt: run.createdAt.toISOString(),
      updatedAt: run.updatedAt.toISOString(),
    },
    participants: items.map(({item, persona, transcript}) => ({
      status: item.status,
      error: item.error,
      persona: personaToJson(persona),
      transcript: transcript ? sessionToJson(transcript) : null,
    })),
  }
  return JSON.stringify(doc, null, 2)
}

/** Versioned, import-ready single-session backup: persona + one session. */
export function buildSessionExportJson(
  persona: Persona,
  transcript: Transcript,
): string {
  const doc: SessionBackupJson = {
    format: 'note-next.session-backup',
    version: 1,
    exportedAt: new Date().toISOString(),
    integrity: EXPORT_INTEGRITY_LINE,
    persona: personaToJson(persona),
    session: sessionToJson(transcript),
  }
  return JSON.stringify(doc, null, 2)
}
